name: Java Compile Check

on:
  pull_request:
    branches:
      - main
      - uat
      - sit
      - uat # or your default branch

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Compile using Maven
        run: mvn clean install
        # If using Gradle instead:
        # run: ./gradlew build --dry-run
